// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChwzbhSFC0d7jGxT8i_pMmBBxDbdv7R74',
    appId: '1:659467617531:web:c27461ec5ffda363d55c5e',
    messagingSenderId: '659467617531',
    projectId: 'canteenapplication-2f10c',
    authDomain: 'canteenapplication-2f10c.firebaseapp.com',
    storageBucket: 'canteenapplication-2f10c.appspot.com',
    measurementId: 'G-KLQS7T45H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoQhidVbwV-WU2xTSYB6Ct_dW0W4Dt9U',
    appId: '1:659467617531:android:4c9fee6f48e5d2b6d55c5e',
    messagingSenderId: '659467617531',
    projectId: 'canteenapplication-2f10c',
    storageBucket: 'canteenapplication-2f10c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnI1s3IEgo6_9bcl_ud6NNw-qiBw3l_Y',
    appId: '1:659467617531:ios:5f98483c59584183d55c5e',
    messagingSenderId: '659467617531',
    projectId: 'canteenapplication-2f10c',
    storageBucket: 'canteenapplication-2f10c.appspot.com',
    androidClientId: '659467617531-ciuig7llc4d70iog3c80e0qp9q9eu5kt.apps.googleusercontent.com',
    iosClientId: '659467617531-aajg1nas337c3mposfi4lk5urk5bng15.apps.googleusercontent.com',
    iosBundleId: 'com.project.campuscrave',
  );
}
